name: CustomHelp
main: Help\Main
version: 0.0.1
api: [3.0.0, 4.0.0]
author: iRainDrop

commands:
 helpme:
  description: "Helps you out with commands and such."
  usage: "/help"
 helpme factions:
  description: "Helps you out with commands and such."
  usage: "/helpme factions"
